import {Ingredient} from './ingredientType'

export const Ingredients : Ingredient[] = [

 {id: 0, name: 'White Creme de Menthe'},
 {id: 1, name: 'Condensed milk'},
 {id: 2, name: 'Cognac'},
 {id: 3, name: 'Sherry'},
 {id: 4, name: 'Tabasco sauce'},
 {id: 5, name: 'Apple Brandy'},
 {id: 6, name: 'St. Germain'},
 {id: 7, name: 'Cinnamon'},
 {id: 8, name: 'Rye Whiskey'},
 {id: 9, name: 'Club soda'},
 {id: 10, name: 'Lillet Blanc'},
 {id: 11, name: 'Goldschlager'},
 {id: 12, name: 'Milk'},
 {id: 13, name: 'White Wine'},
 {id: 14, name: 'Whiskey'},
 {id: 15, name: 'Blended whiskey'},
 {id: 16, name: 'Maraschino cherry'},
 {id: 17, name: 'Apple brandy'},
 {id: 18, name: 'Creme de Cassis'},
 {id: 19, name: 'Applejack'},
 {id: 20, name: 'Orange Curacao'},
 {id: 21, name: 'Everclear'},
 {id: 22, name: 'Sprite'},
 {id: 23, name: 'Beer'},
 {id: 24, name: 'Ginger Beer'},
 {id: 25, name: 'Sugar Syrup'},
 {id: 26, name: 'Triple sec'},
 {id: 27, name: 'Tea'},
 {id: 28, name: 'Advocaat'},
 {id: 29, name: 'Ricard'},
 {id: 30, name: 'Orgeat syrup'},
 {id: 31, name: 'Coffee'},
 {id: 32, name: 'Grain alcohol'},
 {id: 33, name: 'Dubonnet Rouge'},
 {id: 34, name: 'Cloves'},
 {id: 35, name: 'Raspberry vodka'},
 {id: 36, name: 'Godiva liqueur'},
 {id: 37, name: 'Cucumber'},
 {id: 38, name: 'Maraschino Liqueur'},
 {id: 39, name: 'Bitter lemon'},
 {id: 40, name: 'Ice'},
 {id: 41, name: 'Apricot Nectar'},
 {id: 42, name: 'Cream'},
 {id: 43, name: 'Jim Beam'},
 {id: 44, name: 'Irish Whiskey'},
 {id: 45, name: 'Sour mix'},
 {id: 46, name: 'Ginger ale'},
 {id: 47, name: 'Grenadine'},
 {id: 48, name: 'Corn syrup'},
 {id: 49, name: 'Passion fruit juice'},
 {id: 50, name: 'Soy Sauce'},
 {id: 51, name: 'Soda water'},
 {id: 52, name: 'Sugar syrup'},
 {id: 53, name: 'Creme de Mure'},
 {id: 54, name: 'Coconut milk'},
 {id: 55, name: 'Chocolate liqueur'},
 {id: 56, name: 'Sarsaparilla'},
 {id: 57, name: 'Lemon Juice'},
 {id: 58, name: '151 proof rum'},
 {id: 59, name: 'Half-and-half'},
 {id: 60, name: 'Cider'},
 {id: 61, name: 'Blackberry brandy'},
 {id: 62, name: 'pineapple juice'},
 {id: 63, name: 'Fruit juice'},
 {id: 64, name: 'Vanilla extract'},
 {id: 65, name: 'Honey syrup'},
 {id: 66, name: 'Mint'},
 {id: 67, name: 'Oreo cookie'},
 {id: 68, name: 'Absolut Vodka'},
 {id: 69, name: 'Butterscotch schnapps'},
 {id: 70, name: 'Gin'},
 {id: 71, name: 'Brandy'},
 {id: 72, name: 'Yoghurt'},
 {id: 73, name: 'Cranberry juice'},
 {id: 74, name: 'Spiced rum'},
 {id: 75, name: 'Peppermint extract'},
 {id: 76, name: 'Powdered sugar'},
 {id: 77, name: 'Peychaud bitters'},
 {id: 78, name: 'Pineapple'},
 {id: 79, name: 'Coriander'},
 {id: 80, name: 'Cherry liqueur'},
 {id: 81, name: 'Blackberries'},
 {id: 82, name: 'Water'},
 {id: 83, name: 'Grape Soda'},
 {id: 84, name: 'Wine'},
 {id: 85, name: 'Irish cream'},
 {id: 86, name: 'Allspice'},
 {id: 87, name: 'Grape juice'},
 {id: 88, name: 'Blackcurrant cordial'},
 {id: 89, name: 'Angostura Bitters'},
 {id: 90, name: 'Curacao'},
 {id: 91, name: 'Islay single malt Scotch'},
 {id: 92, name: 'Pisang Ambon'},
 {id: 93, name: 'Lavender'},
 {id: 94, name: 'Cardamom'},
 {id: 95, name: 'Chocolate syrup'},
 {id: 96, name: 'Raspberry Liqueur'},
 {id: 97, name: 'Maraschino liqueur'},
 {id: 98, name: 'Mountain Dew'},
 {id: 99, name: 'Butter'},
 {id: 100, name: 'Kiwi liqueur'},
 {id: 101, name: 'Wormwood'},
 {id: 102, name: 'Mint syrup'},
 {id: 103, name: 'Light cream'},
 {id: 104, name: 'Absolut Citron'},
 {id: 105, name: 'Orange Juice'},
 {id: 106, name: 'gin'},
 {id: 107, name: 'Green Chartreuse'},
 {id: 108, name: 'Carbonated water'},
 {id: 109, name: 'Orange spiral'},
 {id: 110, name: 'Strawberries'},
 {id: 111, name: 'Pomegranate juice'},
 {id: 112, name: 'Peach Vodka'},
 {id: 113, name: 'Bailey'},
 {id: 114, name: 'Egg white'},
 {id: 115, name: 'Vanilla ice-cream'},
 {id: 116, name: 'Sugar'},
 {id: 117, name: 'Bitters'},
 {id: 118, name: 'Yellow Chartreuse'},
 {id: 119, name: 'Cherries'},
 {id: 120, name: 'Chocolate'},
 {id: 121, name: 'Red Chili Flakes'},
 {id: 122, name: 'Coca-Cola'},
 {id: 123, name: 'Green Creme de Menthe'},
 {id: 124, name: 'Hot Sauce'},
 {id: 125, name: 'Rye whiskey'},
 {id: 126, name: 'Schweppes Russchian'},
 {id: 127, name: 'Pernod'},
 {id: 128, name: 'Olive Brine'},
 {id: 129, name: 'Limeade'},
 {id: 130, name: 'Tonic water'},
 {id: 131, name: 'Vanilla'},
 {id: 132, name: 'Pepper'},
 {id: 133, name: 'Orange'},
 {id: 134, name: 'Pineapple Juice'},
 {id: 135, name: 'Sherbet'},
 {id: 136, name: 'lemon juice'},
 {id: 137, name: 'Cherry Heering'},
 {id: 138, name: 'Orange juice'},
 {id: 139, name: 'lemon'},
 {id: 140, name: 'Espresso'},
 {id: 141, name: 'Benedictine'},
 {id: 142, name: 'Vermouth'},
 {id: 143, name: 'Sweet Vermouth'},
 {id: 144, name: 'Corona'},
 {id: 145, name: 'Fruit'},
 {id: 146, name: 'Kool-Aid'},
 {id: 147, name: 'Coconut Liqueur'},
 {id: 148, name: '7-up'},
 {id: 149, name: 'Champagne'},
 {id: 150, name: 'Lager'},
 {id: 151, name: 'Coffee brandy'},
 {id: 152, name: 'Dr. Pepper'},
 {id: 153, name: 'Hot Chocolate'},
 {id: 154, name: 'Falernum'},
 {id: 155, name: 'Jello'},
 {id: 156, name: 'Olive'},
 {id: 157, name: 'Tequila'},
 {id: 158, name: 'Asafoetida'},
 {id: 159, name: 'Cayenne pepper'},
 {id: 160, name: 'Amaretto'},
 {id: 161, name: 'Lemon juice'},
 {id: 162, name: 'Dry Vermouth'},
 {id: 163, name: 'Zima'},
 {id: 164, name: 'Guinness stout'},
 {id: 165, name: 'Hot Damn'},
 {id: 166, name: 'Gold rum'},
 {id: 167, name: 'Egg'},
 {id: 168, name: 'Orange peel'},
 {id: 169, name: 'Rosso Vermouth'},
 {id: 170, name: 'Absolut Peppar'},
 {id: 171, name: 'Creme de Cacao'},
 {id: 172, name: 'blackstrap rum'},
 {id: 173, name: 'Brown sugar'},
 {id: 174, name: 'Ouzo'},
 {id: 175, name: 'Absolut Kurant'},
 {id: 176, name: 'Anisette'},
 {id: 177, name: 'Añejo rum'},
 {id: 178, name: 'Thyme'},
 {id: 179, name: 'Red wine'},
 {id: 180, name: 'Port'},
 {id: 181, name: 'Scotch'},
 {id: 182, name: 'Peach schnapps'},
 {id: 183, name: 'Raspberry syrup'},
 {id: 184, name: 'Apricot Brandy'},
 {id: 185, name: 'Root beer'},
 {id: 186, name: 'Elderflower cordial'},
 {id: 187, name: 'demerara Sugar'},
 {id: 188, name: 'Grapefruit Juice'},
 {id: 189, name: 'Peach nectar'},
 {id: 190, name: 'Coconut syrup'},
 {id: 191, name: 'Soda Water'},
 {id: 192, name: 'Tomato Juice'},
 {id: 193, name: 'Lemon-lime soda'},
 {id: 194, name: 'Grapefruit juice'},
 {id: 195, name: 'Peachtree schnapps'},
 {id: 196, name: 'Wild Turkey'},
 {id: 197, name: 'White rum'},
 {id: 198, name: 'Apfelkorn'},
 {id: 199, name: 'Orange bitters'},
 {id: 200, name: 'Malibu rum'},
 {id: 201, name: 'Lime'},
 {id: 202, name: 'Lime juice'},
 {id: 203, name: 'Honey'},
 {id: 204, name: 'Yukon Jack'},
 {id: 205, name: 'Pink lemonade'},
 {id: 206, name: 'Melon Liqueur'},
 {id: 207, name: 'Creme de Banane'},
 {id: 208, name: 'Passion fruit syrup'},
 {id: 209, name: 'Daiquiri mix'},
 {id: 210, name: 'Whisky'},
 {id: 211, name: 'Jägermeister'},
 {id: 212, name: '7-Up'},
 {id: 213, name: 'Orange Bitters'},
 {id: 214, name: 'Fresh Lime Juice'},
 {id: 215, name: 'Vanilla syrup'},
 {id: 216, name: 'Anis'},
 {id: 217, name: 'Jack Daniels'},
 {id: 218, name: 'Aperol'},
 {id: 219, name: 'Bacardi Limon'},
 {id: 220, name: 'Lime vodka'},
 {id: 221, name: 'Nutmeg'},
 {id: 222, name: 'Grand Marnier'},
 {id: 223, name: 'Ginger'},
 {id: 224, name: 'Black pepper'},
 {id: 225, name: 'Tia maria'},
 {id: 226, name: 'Rosemary'},
 {id: 227, name: 'Pina colada mix'},
 {id: 228, name: 'Irish whiskey'},
 {id: 229, name: 'Food coloring'},
 {id: 230, name: 'Absinthe'},
 {id: 231, name: 'Cranberry Juice'},
 {id: 232, name: 'Heavy cream'},
 {id: 233, name: 'Pepsi Cola'},
 {id: 234, name: 'Prosecco'},
 {id: 235, name: 'Apricot brandy'},
 {id: 236, name: 'Passoa'},
 {id: 237, name: 'Frangelico'},
 {id: 238, name: 'Galliano'},
 {id: 239, name: 'Cherry'},
 {id: 240, name: 'Agave syrup'},
 {id: 241, name: 'Jagermeister'},
 {id: 242, name: 'Rosemary Syrup'},
 {id: 243, name: 'Apple juice'},
 {id: 244, name: 'Cointreau'},
 {id: 245, name: 'Figs'},
 {id: 246, name: 'Egg yolk'},
 {id: 247, name: 'Peach brandy'},
 {id: 248, name: 'Lime Juice'},
 {id: 249, name: 'Coffee liqueur'},
 {id: 250, name: 'Drambuie'},
 {id: 251, name: 'Tonic Water'},
 {id: 252, name: 'Strawberry schnapps'},
 {id: 253, name: 'Sirup of roses'},
 {id: 254, name: 'Midori melon liqueur'},
 {id: 255, name: 'orange juice'},
 {id: 256, name: 'Worcestershire Sauce'},
 {id: 257, name: 'Light rum'},
 {id: 258, name: 'Baileys irish cream'},
 {id: 259, name: 'Lemon'},
 {id: 260, name: 'Sambuca'},
 {id: 261, name: 'Maraschino Cherry'},
 {id: 262, name: 'Marshmallows'},
 {id: 263, name: 'Orange Peel'},
 {id: 264, name: 'Chambord raspberry liqueur'},
 {id: 265, name: 'Dark Rum'},
 {id: 266, name: 'Apple'},
 {id: 267, name: 'Celery salt'},
 {id: 268, name: 'Tomato juice'},
 {id: 269, name: 'maraschino liqueur'},
 {id: 270, name: 'Mezcal'},
 {id: 271, name: 'Pineapple juice'},
 {id: 272, name: 'Cocoa powder'},
 {id: 273, name: 'Campari'},
 {id: 274, name: 'Dark rum'},
 {id: 275, name: 'Rum'},
 {id: 276, name: 'Sweet and sour'},
 {id: 277, name: 'Egg Yolk'},
 {id: 278, name: 'Egg White'},
 {id: 279, name: 'Cachaca'},
 {id: 280, name: 'Kiwi'},
 {id: 281, name: 'Almond flavoring'},
 {id: 282, name: 'Banana'},
 {id: 283, name: 'Peach Bitters'},
 {id: 284, name: 'Blended Scotch'},
 {id: 285, name: 'Mango'},
 {id: 286, name: 'Sloe gin'},
 {id: 287, name: 'Lime peel'},
 {id: 288, name: 'Salt'},
 {id: 289, name: 'Lillet'},
 {id: 290, name: 'Carbonated soft drink'},
 {id: 291, name: 'Black Sambuca'},
 {id: 292, name: 'Triple Sec'},
 {id: 293, name: 'Southern Comfort'},
 {id: 294, name: 'Cream of coconut'},
 {id: 295, name: 'Blue Curacao'},
 {id: 296, name: 'Fruit punch'},
 {id: 297, name: 'White Rum'},
 {id: 298, name: 'Ginger Syrup'},
 {id: 299, name: 'Surge'},
 {id: 300, name: 'Vodka'},
 {id: 301, name: 'Whipped cream'},
 {id: 302, name: 'Banana liqueur'},
 {id: 303, name: 'Worcestershire sauce'},
 {id: 304, name: 'Crown Royal'},
 {id: 305, name: 'Iced tea'},
 {id: 306, name: 'Angostura bitters'},
 {id: 307, name: 'Kahlua'},
 {id: 308, name: 'Lemon peel'},
 {id: 309, name: 'Firewater'},
 {id: 310, name: 'Cranberry vodka'},
 {id: 311, name: 'Maple syrup'},
 {id: 312, name: 'Whipping cream'},
 {id: 313, name: 'Cherry Juice'},
 {id: 314, name: 'Tennessee whiskey'},
 {id: 315, name: 'Bourbon'},
 {id: 316, name: 'Pineapple Syrup'},
 {id: 317, name: 'Pisco'},
 {id: 318, name: 'Papaya'},
 {id: 319, name: 'Lemonade'},
 {id: 320, name: 'Cherry brandy'},
 {id: 321, name: 'Fresca'},
 {id: 322, name: 'Cumin seed'},
 {id: 323, name: 'Caramel coloring'}

];